"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { CustomerSessionExit } from "./customer-session-exit";
import styles from "./customer-quotation-comparison.module.css";

type Quote = { id:string; label:string; quotationNumber:string; currency:string; recommended:boolean; costs:Record<string,number>; schedule:{pickupDate:string|null;deliveryDate:string|null;transitDays:number|null;validUntil:string|null}; remarks:string|null; performance:{status:string;averageRating:number|null;totalReviews:number;completedBookings:number;onTimeDelivery:number|null;recommendationRate:number|null}; compliance:{activePartner:boolean;identityVerified:boolean;insuranceVerified:boolean}; scoring:{price:number;quality:number;reliability:number;compliance:number;completeness:number;total:number|null;excludedReason:string|null} };
type Comparison = { reference:string;route:string;shiftingDate:string|null;recommendation:{version:string;explanation:string|null};quotations:Quote[] };
const money=(currency:string,value:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency,maximumFractionDigits:2}).format(value);
const date=(value:string|null)=>value?new Date(value).toLocaleDateString("en-IN",{dateStyle:"medium"}):"Not committed";

export function CustomerQuotationComparison({reference}:{reference:string}){
  const [data,setData]=useState<Comparison|null>(null),[message,setMessage]=useState(""),[loading,setLoading]=useState(true);
  useEffect(()=>{let active=true;void fetch(`/api/public/quotation-comparison?reference=${encodeURIComponent(reference)}`,{cache:"no-store"}).then(async response=>{const result=await response.json();if(!response.ok||!result.success)throw Error(result.message||"Unable to load quotations.");if(active)setData(result.data)}).catch(error=>{if(active)setMessage(error instanceof Error?error.message:"Unable to load quotations.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[reference]);
  return <main className={styles.page}><div className={styles.container}><header><div><p>EM SAFE MOVE</p><h1>Compare your quotations</h1><span>{data?.route||reference}</span>{data?.quotations.length?<b className={styles.count}>{data.quotations.length} quotations received</b>:null}</div><div className={styles.sessionAction}><CustomerSessionExit reference={reference}/></div></header>{loading?<section className={styles.state}>Loading your protected quotations…</section>:message?<section className={styles.state}><p>{message}</p><Link href={`/track?reference=${encodeURIComponent(reference)}`}>Verify mobile / reopen request</Link></section>:!data?.quotations.length?<section className={styles.state}>Your quotation request is active. Vendor offers will appear here after submission.</section>:<><section className={styles.notice}><strong>How EasyMovers recommends an offer</strong><span>{data.recommendation.explanation||"We compare the information currently available for every eligible quotation."} You remain free to choose any eligible offer.</span></section><div className={styles.grid}>{data.quotations.map(quote=><article key={quote.id} className={quote.recommended?styles.recommended:""}>{quote.recommended&&<b className={styles.ribbon}>EM Safe Move Recommended</b>}<div className={styles.title}><div><h2>{quote.label}</h2><small>{quote.performance.status==="NEW_PARTNER"?"New EasyMovers partner":`${quote.performance.averageRating?.toFixed(1)} / 5 · ${quote.performance.totalReviews} reviews`}</small></div><strong>{money(quote.currency,quote.costs.total)}</strong></div><dl><dt>Transportation</dt><dd>{money(quote.currency,quote.costs.transportation)}</dd><dt>Packing</dt><dd>{money(quote.currency,quote.costs.packing)}</dd><dt>Labour</dt><dd>{money(quote.currency,quote.costs.labour)}</dd><dt>Insurance</dt><dd>{money(quote.currency,quote.costs.insurance)}</dd><dt>Tax</dt><dd>{money(quote.currency,quote.costs.tax)}</dd><dt>Discount</dt><dd>− {money(quote.currency,quote.costs.discount)}</dd></dl><section className={styles.metrics}><span><b>{quote.performance.completedBookings}</b> completed moves</span><span><b>{quote.performance.onTimeDelivery===null?"New":`${quote.performance.onTimeDelivery.toFixed(0)}%`}</b> on-time record</span><span><b>{quote.compliance.identityVerified?"Verified":"Under review"}</b> identity</span></section><p className={styles.schedule}>Pickup: {date(quote.schedule.pickupDate)} · Delivery: {date(quote.schedule.deliveryDate)} · Valid until: {date(quote.schedule.validUntil)}</p>{quote.scoring.excludedReason&&<p className={styles.warning}>{quote.scoring.excludedReason}</p>}<button type="button" disabled title="Secure quotation acceptance will be enabled in the next step.">Choose this quotation</button></article>)}</div><p className={styles.next}>Review each offer carefully. Your move is not booked until you choose a quotation and complete booking confirmation.</p></>}</div></main>
}
