"use client";
import {useEffect,useState} from "react";
import styles from "./moving.module.css";
export function DraftAssistance({reference,version,locked,local,beforeRequest,onVersion}:{reference:string;version:string;locked:boolean;local:boolean;beforeRequest:()=>Promise<boolean>;onVersion:(version:string)=>void}){
 const [pricingReady,setPricingReady]=useState<boolean|null>(null);
 useEffect(()=>{if(!local)return;const controller=new AbortController();fetch(`/api/public/local-fare?reference=${encodeURIComponent(reference)}`,{signal:controller.signal,cache:"no-store"}).then(async response=>{const data=await response.json();if(!controller.signal.aborted)setPricingReady(response.ok&&data.configured===true)}).catch(()=>{if(!controller.signal.aborted)setPricingReady(false)});return()=>controller.abort()},[reference,local]);
 const [slot,setSlot]=useState("");const [savedSlot,setSavedSlot]=useState("");const [photos,setPhotos]=useState<{id:string;url?:string}[]>([]);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [fare,setFare]=useState<any>(null);const [vehicle,setVehicle]=useState("");const [vehicles,setVehicles]=useState<{code:string;label:string}[]>([]);const [helpers,setHelpers]=useState(0);
 async function load(){try{const response=await fetch(`/api/public/draft-assistance?reference=${encodeURIComponent(reference)}`,{cache:"no-store"});const data=await response.json();if(data.success){setPhotos(data.photos);setSavedSlot(data.callbackSlot||"")}}catch{setMessage("Could not load saved photos. Please reopen this draft.")}}
 useEffect(()=>{void load()},[reference]);
 useEffect(()=>{if(!fare)return;const timer=setTimeout(()=>setFare(null),Math.max(0,Date.parse(fare.expiresAt)-Date.now()));return()=>clearTimeout(timer)},[fare]);
 async function request(file?:File){if(busy)return;setBusy(true);setMessage("");try{if(!await beforeRequest()){setMessage("Draft saved. Click again to send your assistance request.");return}let body:BodyInit;let headers:Record<string,string>|undefined;if(file){const form=new FormData();form.set("reference",reference);form.set("version",version);form.set("file",file);body=form}else{headers={"Content-Type":"application/json"};body=JSON.stringify({reference,version,slot:`${slot}+05:30`})}const response=await fetch("/api/public/draft-assistance",{method:"POST",headers,body});const data=await response.json();if(!response.ok)throw Error(data.message);onVersion(data.version);setMessage(data.message);await load()}catch(error){setMessage(error instanceof Error?error.message:"Unable to send request.")}finally{setBusy(false)}}
 return <><section className={styles.assistance}><h3>Call EasyMover Expert</h3><p className={styles.muted}>Request a callback and our executive can help complete your inventory.</p><label className={styles.field}>Preferred callback time (India time)<input type="datetime-local" value={slot} disabled={locked||busy} onChange={e=>setSlot(e.target.value)}/></label><button type="button" className={styles.secondary} disabled={locked||busy||!slot} onClick={()=>request()}>Request a callback</button>{savedSlot&&<p>Requested: {new Date(savedSlot).toLocaleString("en-IN",{timeZone:"Asia/Kolkata"})} IST. Our team will confirm the slot.</p>}<h3>Show us what you’re moving</h3><p className={styles.muted}>Up to 10 photos, JPEG, PNG or WebP, 8 MB each. Our executive can review these; photos alone do not provide measured weight or dimensions.</p><input type="file" aria-label="Upload inventory photo" accept="image/jpeg,image/png,image/webp" disabled={locked||busy||photos.length>=10} onChange={e=>{const file=e.target.files?.[0];if(file)void request(file);e.target.value=""}}/><div className={styles.photoList}>{photos.map((photo,index)=><div key={photo.id}>{photo.url?<img src={photo.url} alt={`Saved inventory photo ${index+1}`}/>:<span>Photo {index+1} saved</span>}</div>)}</div></section>{local&&<section className={styles.assistance}><h3>Instant local transport estimate</h3>{pricingReady!==true&&<p className={styles.muted}>{pricingReady===null?"Checking instant pricing...":"Instant pricing is unavailable. Your enquiry and callback request can still be saved."}</p>}{vehicles.length>0&&<label className={styles.field}>Vehicle<select value={vehicle} onChange={e=>{setVehicle(e.target.value);setFare(null)}}>{vehicles.map(item=><option key={item.code} value={item.code}>{item.label}</option>)}</select></label>}<label className={styles.field}>Loading helpers<select value={helpers} onChange={e=>{setHelpers(Number(e.target.value));setFare(null)}}><option value={0}>No helpers</option><option value={1}>1 helper</option><option value={2}>2 helpers</option></select></label><button type="button" className={styles.primary} disabled={busy||locked||pricingReady!==true} onClick={async()=>{setBusy(true);setFare(null);try{const response=await fetch("/api/public/local-fare",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reference,vehicle:vehicle||undefined,helpers})});const data=await response.json();if(!response.ok)throw Error(data.message);setFare(data);setVehicles(data.vehicles);setVehicle(data.vehicle);setMessage("")}catch(error){setMessage(error instanceof Error?error.message:"Unable to estimate fare.")}finally{setBusy(false)}}}>Get instant estimate</button>{fare&&<><h2>{new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(fare.amountPaise/100)}</h2><p>{(fare.distanceMeters/1000).toFixed(1)} km · Valid for up to 5 minutes</p><p className={styles.muted}>{fare.message}</p></>}</section>}{message&&<p role="status">{message}</p>}</>
}
