// Launch catalogue. Unlisted Indian destinations can use verified postal lookup.
export const indianCities = [
  ["Bhopal", "Madhya Pradesh"],
  ["Jabalpur", "Madhya Pradesh"],
  ["Indore", "Madhya Pradesh"],
  ["Gwalior", "Madhya Pradesh"],
  ["Ujjain", "Madhya Pradesh"],
  ["Sagar", "Madhya Pradesh"],
  ["Satna", "Madhya Pradesh"],
  ["Rewa", "Madhya Pradesh"],
  ["Katni", "Madhya Pradesh"],
  ["Mumbai", "Maharashtra"],
  ["Pune", "Maharashtra"],
  ["Nashik", "Maharashtra"],
  ["Nagpur", "Maharashtra"],
  ["Thane", "Maharashtra"],
  ["Chhatrapati Sambhajinagar", "Maharashtra"],
  ["Delhi", "Delhi"],
  ["New Delhi", "Delhi"],
  ["Noida", "Uttar Pradesh"],
  ["Ghaziabad", "Uttar Pradesh"],
  ["Gurugram", "Haryana"],
  ["Faridabad", "Haryana"],
  ["Bengaluru", "Karnataka"],
  ["Mysuru", "Karnataka"],
  ["Mangaluru", "Karnataka"],
  ["Hyderabad", "Telangana"],
  ["Chennai", "Tamil Nadu"],
  ["Coimbatore", "Tamil Nadu"],
  ["Madurai", "Tamil Nadu"],
  ["Kolkata", "West Bengal"],
  ["Ahmedabad", "Gujarat"],
  ["Surat", "Gujarat"],
  ["Vadodara", "Gujarat"],
  ["Rajkot", "Gujarat"],
  ["Jaipur", "Rajasthan"],
  ["Jodhpur", "Rajasthan"],
  ["Udaipur", "Rajasthan"],
  ["Kota", "Rajasthan"],
  ["Lucknow", "Uttar Pradesh"],
  ["Kanpur", "Uttar Pradesh"],
  ["Varanasi", "Uttar Pradesh"],
  ["Agra", "Uttar Pradesh"],
  ["Prayagraj", "Uttar Pradesh"],
  ["Chandigarh", "Chandigarh"],
  ["Ludhiana", "Punjab"],
  ["Amritsar", "Punjab"],
  ["Patna", "Bihar"],
  ["Ranchi", "Jharkhand"],
  ["Raipur", "Chhattisgarh"],
  ["Bhilai", "Chhattisgarh"],
  ["Bhubaneswar", "Odisha"],
  ["Cuttack", "Odisha"],
  ["Guwahati", "Assam"],
  ["Shillong", "Meghalaya"],
  ["Dehradun", "Uttarakhand"],
  ["Haridwar", "Uttarakhand"],
  ["Jammu", "Jammu and Kashmir"],
  ["Srinagar", "Jammu and Kashmir"],
  ["Kochi", "Kerala"],
  ["Thiruvananthapuram", "Kerala"],
  ["Kozhikode", "Kerala"],
  ["Visakhapatnam", "Andhra Pradesh"],
  ["Vijayawada", "Andhra Pradesh"],
  ["Tirupati", "Andhra Pradesh"],
  ["Panaji", "Goa"],
  ["Puducherry", "Puducherry"],
  ["Shimla", "Himachal Pradesh"],
  ["Gangtok", "Sikkim"],
  ["Agartala", "Tripura"],
  ["Imphal", "Manipur"],
  ["Aizawl", "Mizoram"],
  ["Kohima", "Nagaland"],
  ["Itanagar", "Arunachal Pradesh"],
  ["Port Blair", "Andaman and Nicobar Islands"],
].map(([city, state]) => ({ city, state, label: `${city}, ${state}` }));
export function findIndianCity(value: string) {
  const aliases: Record<string, string> = {
    bangalore: "bengaluru",
    bombay: "mumbai",
    nasik: "nashik",
    calcutta: "kolkata",
    gurgaon: "gurugram",
  };
  const normalized = value.trim().toLowerCase();
  const city = aliases[normalized] || normalized;
  return indianCities.find(
    (item) =>
      item.label.toLowerCase() === normalized ||
      item.city.toLowerCase() === city,
  );
}
