"use client";

import { createClient } from "@supabase/supabase-js";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import styles from "./commercial-term-admin.module.css";

type Candidate = { paymentId:string;paymentNumber:string;bookingNumber:string;customerPayableAmount:number;currency:string;quotationId:string;quotationNumber:string;vendorId:string;vendorQuotedAmount:number;vendor:{vendorCode:string;companyName:string} };
type TermRequest = { id:string;customerPayableAmount:string;vendorQuotedAmount:string;platformCommissionAmount:string;currency:string;status:string;submissionNote:string|null;reviewNote:string|null;submittedBy:string;reviewedBy:string|null;submittedAt:string;reviewedAt:string|null;appliedAt:string|null;vendor:{vendorCode:string;companyName:string};payment:{paymentNumber:string;booking:{bookingNumber:string}};quotation:{quotationNumber:string} };
const money=(value:number|string,code="INR")=>new Intl.NumberFormat("en-IN",{style:"currency",currency:code,maximumFractionDigits:2}).format(Number(value));

export function CommercialTermAdmin({supabaseUrl,publishableKey,initialStatus="PENDING"}:{supabaseUrl:string;publishableKey:string;initialStatus?:string}) {
  const router=useRouter();
  const client=useMemo(()=>supabaseUrl&&publishableKey?createClient(supabaseUrl,publishableKey):null,[supabaseUrl,publishableKey]);
  const [candidates,setCandidates]=useState<Candidate[]>([]); const [requests,setRequests]=useState<TermRequest[]>([]); const [currentUserId,setCurrentUserId]=useState("");
  const [status,setStatus]=useState(initialStatus); const [candidateId,setCandidateId]=useState(""); const [selectedId,setSelectedId]=useState("");
  const [commission,setCommission]=useState(""); const [submissionNote,setSubmissionNote]=useState(""); const [reviewNote,setReviewNote]=useState("");
  const [message,setMessage]=useState(""); const [success,setSuccess]=useState(false); const [busy,setBusy]=useState(false);
  const request=useCallback(async(path:string,init?:RequestInit)=>{if(!client)throw new Error("Office authentication is not configured.");const {data}=await client.auth.getSession();if(!data.session){router.replace("/admin/login?returnTo=/admin/commercial-terms");throw new Error("Office session expired.");}const response=await fetch(path,{...init,cache:"no-store",headers:{Authorization:`Bearer ${data.session.access_token}`,...(init?.body?{"Content-Type":"application/json"}:{}),...init?.headers}});const payload=await response.json();if(!response.ok||!payload.success)throw new Error(payload?.error?.message||"Commission operation failed.");return payload.data;},[client,router]);
  const load=useCallback(async()=>{setBusy(true);setMessage("");try{const data=await request(`/api/admin/commercial-terms?status=${status}`);setCandidates(data.candidates);setRequests(data.requests);setCurrentUserId(data.currentUserId);setSelectedId((id:string)=>data.requests.some((item:TermRequest)=>item.id===id)?id:data.requests[0]?.id||"");}catch(error){setSuccess(false);setMessage(error instanceof Error?error.message:"Unable to load commission control.");}finally{setBusy(false);}},[request,status]);
  useEffect(()=>{void load();},[load]);
  const candidate=candidates.find(item=>item.paymentId===candidateId)||null; const selected=requests.find(item=>item.id===selectedId)||null; const ownRequest=selected?.submittedBy===currentUserId;
  const commissionValue=Number(commission)||0; const vendorNet=candidate?candidate.vendorQuotedAmount-commissionValue:0; const commissionRate=candidate&&candidate.vendorQuotedAmount?commissionValue/candidate.vendorQuotedAmount*100:0;
  async function act(path:string,body:unknown,successMessage:string){setBusy(true);setMessage("");try{await request(path,{method:"POST",body:JSON.stringify(body)});setSuccess(true);setMessage(successMessage);setCommission("");setSubmissionNote("");setReviewNote("");setCandidateId("");await load();}catch(error){setSuccess(false);setMessage(error instanceof Error?error.message:"Commission operation failed.");}finally{setBusy(false);}}
  return <main className={styles.page}><header><div><p>FINANCE CONTROL</p><h1>Commission readiness</h1><span>Lock EasyMovers commission through independent maker-checker approval before vendor settlement.</span></div><div><Link href="/admin/vendor-settlements">Vendor settlements</Link><button onClick={()=>void load()} disabled={busy}>Refresh</button></div></header>
    {message&&<p className={success?styles.success:styles.error}>{message}</p>}
    <section className={styles.create}><div><h2>Submit commercial terms</h2><p>Only payments linked to the booking&apos;s accepted quotation appear here.</p></div><label>Accepted booking<select value={candidateId} onChange={event=>{setCandidateId(event.target.value);setCommission("");}}><option value="">Select vendor and booking</option>{candidates.map(item=><option key={item.paymentId} value={item.paymentId}>{item.vendor.companyName} · {item.bookingNumber} · quote {money(item.vendorQuotedAmount,item.currency)}</option>)}</select></label>{candidate&&<div className={styles.summary}><span>Customer payable<strong>{money(candidate.customerPayableAmount,candidate.currency)}</strong></span><span>Vendor quotation<strong>{money(candidate.vendorQuotedAmount,candidate.currency)}</strong></span><span>Vendor net after commission<strong>{money(vendorNet,candidate.currency)}</strong></span><span>Commission rate<strong>{commissionRate.toFixed(2)}%</strong></span></div>}<label>EasyMovers commission<input type="number" min="0" step="0.01" max={candidate?.vendorQuotedAmount} value={commission} onChange={event=>setCommission(event.target.value)} placeholder="0.00"/></label><label>Maker note<input value={submissionNote} maxLength={1000} onChange={event=>setSubmissionNote(event.target.value)} placeholder="Commercial approval or rate reference"/></label><button disabled={busy||!candidate||commission===""||commissionValue<0||commissionValue>candidate.vendorQuotedAmount} onClick={()=>candidate&&void act("/api/admin/commercial-terms",{paymentId:candidate.paymentId,platformCommissionAmount:commission,submissionNote},"Commission submitted for independent approval.")}>Submit for approval</button></section>
    <section className={styles.toolbar}><label>Queue<select value={status} onChange={event=>setStatus(event.target.value)}><option value="PENDING">Awaiting checker</option><option value="APPROVED">Approved</option><option value="REJECTED">Rejected</option><option value="CANCELLED">Cancelled</option></select></label><span>{requests.length} request{requests.length===1?"":"s"}</span></section>
    <div className={styles.workspace}><section className={styles.list}>{requests.length?requests.map(item=><button key={item.id} className={item.id===selectedId?styles.selected:""} onClick={()=>{setSelectedId(item.id);setMessage("");}}><span><strong>{item.vendor.companyName}</strong><em>{item.status}</em></span><b>{money(item.platformCommissionAmount,item.currency)}</b><small>{item.payment.booking.bookingNumber} · {item.quotation.quotationNumber}</small></button>):<p>No commission requests in this queue.</p>}</section><section className={styles.detail}>{!selected?<p>Select a request to review.</p>:<><div className={styles.title}><div><span>{selected.vendor.vendorCode}</span><h2>{selected.vendor.companyName}</h2><p>{selected.payment.booking.bookingNumber} · {selected.payment.paymentNumber}</p></div><strong>{money(selected.platformCommissionAmount,selected.currency)}</strong></div><dl><div><dt>Customer payable</dt><dd>{money(selected.customerPayableAmount,selected.currency)}</dd></div><div><dt>Vendor quotation</dt><dd>{money(selected.vendorQuotedAmount,selected.currency)}</dd></div><div><dt>Vendor net</dt><dd>{money(Number(selected.vendorQuotedAmount)-Number(selected.platformCommissionAmount),selected.currency)}</dd></div><div><dt>Submitted</dt><dd>{new Date(selected.submittedAt).toLocaleString("en-IN")}</dd></div></dl>{selected.submissionNote&&<p className={styles.note}><b>Maker note:</b> {selected.submissionNote}</p>}{selected.status==="PENDING"&&<div className={styles.action}><h3>Independent checker decision</h3>{ownRequest&&<p className={styles.warning}>You created this request. Another authorised checker must review it.</p>}<textarea value={reviewNote} onChange={event=>setReviewNote(event.target.value)} placeholder="Reason required for rejection"/><div><button disabled={busy||ownRequest} onClick={()=>void act(`/api/admin/commercial-terms/${selected.id}/review`,{decision:"APPROVED",reviewNote},"Commission approved and locked. The funded booking can now enter the settlement workflow.")}>Approve and lock</button><button className={styles.danger} disabled={busy||ownRequest||!reviewNote.trim()} onClick={()=>void act(`/api/admin/commercial-terms/${selected.id}/review`,{decision:"REJECTED",reviewNote},"Commission request rejected.")}>Reject</button></div></div>}{selected.status==="APPROVED"&&<p className={styles.approved}>Commission is locked. Once customer funds are received, this booking is available in the vendor settlement dropdown.</p>}{selected.reviewNote&&<p className={styles.note}><b>Checker note:</b> {selected.reviewNote}</p>}</>}</section></div>
  </main>;
}
