"use client";

import { createClient } from "@supabase/supabase-js";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import styles from "./vendor-settlement-admin.module.css";

type Candidate={paymentId:string;paymentNumber:string;bookingNumber:string;customerPayableAmount:number;currency:string;quotationId:string;quotationNumber:string;vendorId:string;vendorQuotedAmount:number;vendor:{vendorCode:string;companyName:string;gstNumber:string|null;state:string|null}};
type TermRequest={id:string;paymentId:string;customerPayableAmount:string;vendorQuotedAmount:string;platformCommissionAmount:string;commissionRate:string;commissionBase:string;gstTreatment:string;gstRate:string;cgstAmount:string;sgstAmount:string;igstAmount:string;tcsApplicable:boolean;tcsRate:string;tcsBase:string;tcsAmount:string;placeOfSupplyState:string|null;vendorGstinSnapshot:string|null;easymoversGstinSnapshot:string|null;taxOverrideReason:string|null;revisedFromId:string|null;revisionNumber:number;currency:string;status:string;submissionNote:string|null;reviewNote:string|null;submittedBy:string;reviewedBy:string|null;submittedAt:string;reviewedAt:string|null;appliedAt:string|null;vendor:{vendorCode:string;companyName:string};payment:{paymentNumber:string;booking:{bookingNumber:string}};quotation:{quotationNumber:string}};
const money=(value:number|string,code="INR")=>new Intl.NumberFormat("en-IN",{style:"currency",currency:code,maximumFractionDigits:2}).format(Number(value));
const round=(value:number)=>Math.round((value+Number.EPSILON)*100)/100;

export function CommercialTermAdmin({supabaseUrl,publishableKey,initialStatus="PENDING"}:{supabaseUrl:string;publishableKey:string;initialStatus?:string}){
  const router=useRouter();
  const client=useMemo(()=>supabaseUrl&&publishableKey?createClient(supabaseUrl,publishableKey):null,[supabaseUrl,publishableKey]);
  const [candidates,setCandidates]=useState<Candidate[]>([]),[requests,setRequests]=useState<TermRequest[]>([]),[currentUserId,setCurrentUserId]=useState("");
  const [status,setStatus]=useState(initialStatus),[candidateId,setCandidateId]=useState(""),[selectedId,setSelectedId]=useState(""),[revisedFromId,setRevisedFromId]=useState("");
  const [commissionRate,setCommissionRate]=useState("10"),[gstTreatment,setGstTreatment]=useState("CGST_SGST"),[gstRate,setGstRate]=useState("18"),[placeOfSupplyState,setPlaceOfSupplyState]=useState("");
  const [tcsApplicable,setTcsApplicable]=useState(false),[tcsRate,setTcsRate]=useState("0.5"),[taxOverrideReason,setTaxOverrideReason]=useState(""),[submissionNote,setSubmissionNote]=useState(""),[reviewNote,setReviewNote]=useState("");
  const [message,setMessage]=useState(""),[success,setSuccess]=useState(false),[busy,setBusy]=useState(false);

  const request=useCallback(async(path:string,init?:RequestInit)=>{if(!client)throw new Error("Office authentication is not configured.");const{data}=await client.auth.getSession();if(!data.session){router.replace("/admin/login?returnTo=/admin/commercial-terms");throw new Error("Office session expired.");}const response=await fetch(path,{...init,cache:"no-store",headers:{Authorization:`Bearer ${data.session.access_token}`,...(init?.body?{"Content-Type":"application/json"}:{}),...init?.headers}});const payload=await response.json();if(!response.ok||!payload.success){if(payload?.error?.code==="CRM_PERMISSION_REQUIRED")throw new Error("Commission readiness requires Payment Read access. Assign Finance Executive, Finance Manager or CRM Administrator in Office users.");throw new Error(payload?.error?.message||"Commission operation failed.");}return payload.data;},[client,router]);
  const load=useCallback(async()=>{setBusy(true);try{const data=await request(`/api/admin/commercial-terms?status=${status}`);setCandidates(data.candidates);setRequests(data.requests);setCurrentUserId(data.currentUserId);setSelectedId((id:string)=>data.requests.some((item:TermRequest)=>item.id===id)?id:data.requests[0]?.id||"");}catch(error){setSuccess(false);setMessage(error instanceof Error?error.message:"Unable to load commission control.");}finally{setBusy(false);}},[request,status]);
  useEffect(()=>{void load();},[load]);
  const candidate=candidates.find(item=>item.paymentId===candidateId)||null,selected=requests.find(item=>item.id===selectedId)||null,ownRequest=selected?.submittedBy===currentUserId;
  const base=candidate?.vendorQuotedAmount||0,rate=Number(commissionRate)||0,commission=round(base*rate/100),gstPercent=gstTreatment==="NOT_APPLICABLE"?0:Number(gstRate)||0,gst=round(commission*gstPercent/100);
  const cgst=gstTreatment==="CGST_SGST"?round(gst/2):0,sgst=gstTreatment==="CGST_SGST"?round(gst-cgst):0,igst=gstTreatment==="IGST"?gst:0,tcs=tcsApplicable?round(base*(Number(tcsRate)||0)/100):0;
  const platformInvoice=round(commission+cgst+sgst+igst),vendorNet=round(base-platformInvoice-tcs);
  function resetForm(){setCandidateId("");setRevisedFromId("");setCommissionRate("10");setGstTreatment("CGST_SGST");setGstRate("18");setPlaceOfSupplyState("");setTcsApplicable(false);setTcsRate("0.5");setTaxOverrideReason("");setSubmissionNote("");}
  async function act(path:string,body:unknown,successMessage:string){setBusy(true);setMessage("");try{await request(path,{method:"POST",body:JSON.stringify(body)});setSuccess(true);setMessage(successMessage);resetForm();setReviewNote("");await load();}catch(error){setSuccess(false);setMessage(error instanceof Error?error.message:"Commission operation failed.");}finally{setBusy(false);}}
  function revise(item:TermRequest){const match=candidates.find(candidate=>candidate.paymentId===item.paymentId);if(!match){setSuccess(false);setMessage("This payment is no longer eligible for revision. Refresh or check whether another request is pending.");return;}setCandidateId(match.paymentId);setRevisedFromId(item.id);setCommissionRate(String(item.commissionRate));setGstTreatment(item.gstTreatment==="PENDING_REVIEW"?"CGST_SGST":item.gstTreatment);setGstRate(item.gstTreatment==="PENDING_REVIEW"?"18":String(item.gstRate));setPlaceOfSupplyState(item.placeOfSupplyState||match.vendor.state||"");setTcsApplicable(item.tcsApplicable);setTcsRate(String(item.tcsRate||"0.5"));setTaxOverrideReason(item.taxOverrideReason||"");setSubmissionNote(item.submissionNote||"");window.scrollTo({top:0,behavior:"smooth"});}
  const canSubmit=!!candidate&&rate>=0&&rate<=100&&gstPercent>=0&&gstPercent<=100&&vendorNet>=0&&(gstTreatment!=="NOT_APPLICABLE"||!!taxOverrideReason.trim());

  return <main className={styles.page}><header><div><p>FINANCE CONTROL</p><h1>Commission &amp; tax readiness</h1><span>Approve an immutable commission and tax snapshot before settlement.</span></div><div className={styles.headerActions}><Link href="/admin/vendor-settlements">Vendor settlements</Link><button onClick={()=>void load()} disabled={busy}>Refresh</button></div></header>
    {message&&<p className={success?styles.success:styles.error}>{message}</p>}
    <section className={styles.create}><div><h2>{revisedFromId?"Revise rejected terms":"Submit commercial terms"}</h2><p>{revisedFromId?"The rejected record remains unchanged; this creates a linked revision.":"Tax values are calculated from the accepted vendor quotation."}</p></div>
      <label className={styles.wide}>Accepted booking<select value={candidateId} onChange={event=>{setCandidateId(event.target.value);setRevisedFromId("");const next=candidates.find(item=>item.paymentId===event.target.value);setPlaceOfSupplyState(next?.vendor.state||"");}}><option value="">Select vendor and booking</option>{candidates.map(item=><option key={item.paymentId} value={item.paymentId}>{item.vendor.companyName} · {item.bookingNumber} · {money(item.vendorQuotedAmount,item.currency)}</option>)}</select></label>
      {candidate&&<div className={styles.summary}><span>Vendor quotation<strong>{money(base,candidate.currency)}</strong></span><span>Commission ({rate.toFixed(2)}%)<strong>{money(commission,candidate.currency)}</strong></span><span>GST on commission<strong>{money(gst,candidate.currency)}</strong></span><span>Platform invoice<strong>{money(platformInvoice,candidate.currency)}</strong></span><span>TCS withholding<strong>{money(tcs,candidate.currency)}</strong></span><span>Estimated vendor net<strong>{money(vendorNet,candidate.currency)}</strong></span></div>}
      <label>Commission rate %<input type="number" min="0" max="100" step="0.01" value={commissionRate} onChange={event=>setCommissionRate(event.target.value)}/></label>
      <label>GST treatment<select value={gstTreatment} onChange={event=>{setGstTreatment(event.target.value);if(event.target.value==="NOT_APPLICABLE")setGstRate("0");else if(gstRate==="0")setGstRate("18");}}><option value="CGST_SGST">CGST + SGST (intra-state)</option><option value="IGST">IGST (inter-state)</option><option value="NOT_APPLICABLE">Not applicable</option></select></label>
      <label>GST rate %<input type="number" min="0" max="100" step="0.01" disabled={gstTreatment==="NOT_APPLICABLE"} value={gstRate} onChange={event=>setGstRate(event.target.value)}/></label>
      <label>Place of supply<input value={placeOfSupplyState} maxLength={100} onChange={event=>setPlaceOfSupplyState(event.target.value)} placeholder="State or union territory"/></label>
      <label className={styles.check}><input type="checkbox" checked={tcsApplicable} onChange={event=>setTcsApplicable(event.target.checked)}/> TCS applicable</label>
      <label>TCS rate %<input type="number" min="0" max="100" step="0.01" disabled={!tcsApplicable} value={tcsRate} onChange={event=>setTcsRate(event.target.value)}/></label>
      <label className={styles.wide}>Tax exception / override reason<input value={taxOverrideReason} maxLength={500} onChange={event=>setTaxOverrideReason(event.target.value)} placeholder="Required when GST is not applicable"/></label>
      <label className={styles.wide}>Maker note<input value={submissionNote} maxLength={1000} onChange={event=>setSubmissionNote(event.target.value)} placeholder="Agreement, approval or rate reference"/></label>
      <button disabled={busy||!canSubmit} onClick={()=>candidate&&void act("/api/admin/commercial-terms",{paymentId:candidate.paymentId,commissionRate,gstTreatment,gstRate,tcsApplicable,tcsRate,placeOfSupplyState,taxOverrideReason,revisedFromId:revisedFromId||undefined,submissionNote},revisedFromId?"Revised commercial terms submitted for independent approval.":"Commission and tax terms submitted for independent approval.")}>{revisedFromId?"Submit revision":"Submit for approval"}</button>
    </section>
    <section className={styles.toolbar}><label>Queue<select value={status} onChange={event=>setStatus(event.target.value)}><option value="PENDING">Awaiting checker</option><option value="APPROVED">Approved</option><option value="REJECTED">Rejected</option><option value="CANCELLED">Cancelled</option></select></label><span>{requests.length} request{requests.length===1?"":"s"}</span></section>
    <div className={styles.workspace}><section className={styles.list}>{requests.length?requests.map(item=><button key={item.id} className={item.id===selectedId?styles.selected:""} onClick={()=>{setSelectedId(item.id);setMessage("");}}><span><strong>{item.vendor.companyName}</strong><em>{item.status}</em></span><b>{Number(item.commissionRate).toFixed(2)}% · {money(item.platformCommissionAmount,item.currency)}</b><small>{item.payment.booking.bookingNumber} · revision {item.revisionNumber}</small></button>):<p>No commission requests in this queue.</p>}</section>
      <section className={styles.detail}>{!selected?<p>Select a request to review.</p>:<><div className={styles.title}><div><span>{selected.vendor.vendorCode} · revision {selected.revisionNumber}</span><h2>{selected.vendor.companyName}</h2><p>{selected.payment.booking.bookingNumber} · {selected.payment.paymentNumber}</p></div><strong>{money(selected.platformCommissionAmount,selected.currency)}</strong></div>
        <dl><div><dt>Commission rate</dt><dd>{Number(selected.commissionRate).toFixed(2)}%</dd></div><div><dt>Commission base</dt><dd>{money(selected.commissionBase,selected.currency)}</dd></div><div><dt>GST treatment</dt><dd>{selected.gstTreatment.replace("_"," + ")}</dd></div><div><dt>GST rate</dt><dd>{Number(selected.gstRate).toFixed(2)}%</dd></div><div><dt>CGST / SGST / IGST</dt><dd>{money(selected.cgstAmount)} / {money(selected.sgstAmount)} / {money(selected.igstAmount)}</dd></div><div><dt>TCS</dt><dd>{selected.tcsApplicable?`${Number(selected.tcsRate).toFixed(2)}% · ${money(selected.tcsAmount)}`:"Not applicable"}</dd></div><div><dt>Place of supply</dt><dd>{selected.placeOfSupplyState||"Not recorded"}</dd></div><div><dt>Vendor GSTIN</dt><dd>{selected.vendorGstinSnapshot||"Not recorded"}</dd></div><div><dt>Submitted</dt><dd>{new Date(selected.submittedAt).toLocaleString("en-IN")}</dd></div></dl>
        {selected.submissionNote&&<p className={styles.note}><b>Maker note:</b> {selected.submissionNote}</p>}{selected.taxOverrideReason&&<p className={styles.warning}><b>Tax exception:</b> {selected.taxOverrideReason}</p>}
        {selected.status==="PENDING"&&<div className={styles.action}><h3>Independent checker decision</h3>{ownRequest&&<p className={styles.warning}>You created this request. Another authorised checker must review it.</p>}<textarea value={reviewNote} onChange={event=>setReviewNote(event.target.value)} placeholder="Reason required for rejection"/><div><button disabled={busy||ownRequest} onClick={()=>void act(`/api/admin/commercial-terms/${selected.id}/review`,{decision:"APPROVED",reviewNote},"Commission and tax snapshot approved and locked.")}>Approve and lock</button><button className={styles.danger} disabled={busy||ownRequest||!reviewNote.trim()} onClick={()=>void act(`/api/admin/commercial-terms/${selected.id}/review`,{decision:"REJECTED",reviewNote},"Commission request rejected. The maker can revise and resubmit it.")}>Reject</button></div></div>}
        {selected.status==="REJECTED"&&<div className={styles.action}><button onClick={()=>revise(selected)} disabled={busy}>Revise and resubmit</button></div>}{selected.status==="APPROVED"&&<p className={styles.approved}>The approved commercial and tax snapshot is locked for settlement. A numbered tax invoice will be generated only after the platform fee becomes earned.</p>}{selected.reviewNote&&<p className={styles.note}><b>Checker note:</b> {selected.reviewNote}</p>}</>}</section>
    </div>
  </main>;
}
