"use client";

import {createClient} from "@supabase/supabase-js";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {useCallback,useEffect,useMemo,useState} from "react";
import styles from "./finance-monthly-collections.module.css";

type Values={bookings:number;collections:number;refunds:number;netCollections:number;commissionIncome:number;gst:number;tcs:number;vendorPayable:number;vendorSettledInMonth:number;vendorOutstanding:number;customerOutstanding:number};
type Row={id:string;paymentNumber:string;bookingNumber:string;businessSegment:string;serviceType:string;moveType:string;route:string;vendor:{vendorCode:string;companyName:string}|null;currency:string;collections:number;refunds:number;netCollections:number;commissionIncome:number;gst:number;tcs:number;vendorPayable:number;vendorSettledInMonth:number;vendorOutstanding:number;customerOutstanding:number};
type Report={month:string;timezone:string;segment:string|null;total:Values;bySegment:Record<string,Values>;rows:Row[];generatedAt:string;notes:{income:string;collections:string;gatewayCharges:string}};
const segments=["WITHIN_CITY_INSTANT","WITHIN_CITY_QUOTATION","INTERCITY_QUOTATION","CORPORATE_RELOCATION","ADD_ON_SERVICE"];
const label=(value:string)=>value.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,character=>character.toUpperCase());
const money=(value:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(value);
const currentMonth=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit"}).format(new Date()).slice(0,7);

export function FinanceMonthlyCollections({supabaseUrl,publishableKey}:{supabaseUrl:string;publishableKey:string}){
  const router=useRouter(),client=useMemo(()=>supabaseUrl&&publishableKey?createClient(supabaseUrl,publishableKey):null,[supabaseUrl,publishableKey]);
  const [month,setMonth]=useState(currentMonth()),[segment,setSegment]=useState(""),[applied,setApplied]=useState({month:currentMonth(),segment:""});
  const [data,setData]=useState<Report|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const load=useCallback(async()=>{setBusy(true);setError("");try{if(!client)throw new Error("Office authentication is not configured.");const{data:session}=await client.auth.getSession();if(!session.session){router.replace("/admin/login?returnTo=/admin/finance");throw new Error("Office session expired.");}const query=new URLSearchParams({month:applied.month});if(applied.segment)query.set("segment",applied.segment);const response=await fetch(`/api/admin/finance/collections?${query}`,{cache:"no-store",headers:{Authorization:`Bearer ${session.session.access_token}`}});const payload=await response.json();if(!response.ok||!payload.success)throw new Error(payload?.error?.message||"Unable to load finance report.");setData(payload.data);}catch(reason){setError(reason instanceof Error?reason.message:"Unable to load finance report.");}finally{setBusy(false);}},[applied,client,router]);
  useEffect(()=>{void load();},[load]);
  const withinCity=(data?.bySegment.WITHIN_CITY_INSTANT?.commissionIncome||0)+(data?.bySegment.WITHIN_CITY_QUOTATION?.commissionIncome||0);
  const intercity=data?.bySegment.INTERCITY_QUOTATION?.commissionIncome||0;
  return <main className={styles.page}><header><div><p>FINANCE &amp; COLLECTIONS</p><h1>Monthly financial overview</h1><span>Separate customer money, EasyMovers income, taxes and vendor liabilities.</span></div><div className={styles.links}><Link href="/admin/commercial-terms">Commission &amp; tax</Link><Link href="/admin/tax-invoices">Tax invoices</Link><Link href="/admin/vendor-settlements">Settlements</Link></div></header>
    <form className={styles.filters} onSubmit={event=>{event.preventDefault();setApplied({month,segment});}}><label>Financial month<input type="month" value={month} onChange={event=>setMonth(event.target.value)} required/></label><label>Business segment<select value={segment} onChange={event=>setSegment(event.target.value)}><option value="">All segments</option>{segments.map(item=><option key={item} value={item}>{label(item)}</option>)}</select></label><button disabled={busy}>{busy?"Loading…":"Apply"}</button><button type="button" onClick={()=>void load()} disabled={busy}>Refresh</button></form>
    {error&&<p className={styles.error}>{error}</p>}{data&&<><section className={styles.cards}><article><span>Customer collections</span><strong>{money(data.total.collections)}</strong><small>Successful collection transactions</small></article><article><span>Net collections</span><strong>{money(data.total.netCollections)}</strong><small>Collections less refunds</small></article><article className={styles.income}><span>EasyMovers commission income</span><strong>{money(data.total.commissionIncome)}</strong><small>Excludes GST and customer funds</small></article><article><span>Within-city income</span><strong>{money(withinCity)}</strong><small>Instant + quotation commission</small></article><article><span>Intercity income</span><strong>{money(intercity)}</strong><small>Intercity quotation commission</small></article><article className={styles.tax}><span>GST liability snapshot</span><strong>{money(data.total.gst)}</strong><small>CGST/SGST/IGST on commission</small></article><article><span>Vendor paid this month</span><strong>{money(data.total.vendorSettledInMonth)}</strong><small>Completed settlements</small></article><article className={styles.alert}><span>Vendor outstanding</span><strong>{money(data.total.vendorOutstanding)}</strong><small>Current payable on included bookings</small></article></section>
      <section className={styles.panel}><div><h2>Income by business segment</h2><p>Commission is income; GST, TCS and vendor value are tracked separately.</p></div><div className={styles.tableWrap}><table><thead><tr><th>Segment</th><th>Bookings</th><th>Collections</th><th>Commission income</th><th>GST</th><th>TCS</th><th>Vendor payable</th><th>Settled</th></tr></thead><tbody>{segments.map(item=>{const row=data.bySegment[item];return <tr key={item}><th>{label(item)}</th><td>{row.bookings}</td><td>{money(row.collections)}</td><td>{money(row.commissionIncome)}</td><td>{money(row.gst)}</td><td>{money(row.tcs)}</td><td>{money(row.vendorPayable)}</td><td>{money(row.vendorSettledInMonth)}</td></tr>;})}</tbody></table></div></section>
      <section className={styles.panel}><div><h2>Monthly transaction drill-down</h2><p>{data.rows.length} payment record{data.rows.length===1?"":"s"} in {data.month}.</p></div><div className={styles.tableWrap}><table><thead><tr><th>Booking / payment</th><th>Segment</th><th>Route and vendor</th><th>Collected</th><th>Refunded</th><th>EM income</th><th>GST</th><th>Vendor settled</th><th>Outstanding</th></tr></thead><tbody>{data.rows.length?data.rows.map(row=><tr key={row.id}><th>{row.bookingNumber}<small>{row.paymentNumber}</small></th><td>{label(row.businessSegment)}</td><td>{row.route}<small>{row.vendor?.companyName||"Vendor not assigned"}</small></td><td>{money(row.collections)}</td><td>{money(row.refunds)}</td><td>{money(row.commissionIncome)}</td><td>{money(row.gst)}</td><td>{money(row.vendorSettledInMonth)}</td><td>{money(row.vendorOutstanding)}</td></tr>):<tr><td colSpan={9}>No successful financial activity was recorded for this selection.</td></tr>}</tbody></table></div></section>
      <section className={styles.notes}><p>{data.notes.income}</p><p>{data.notes.collections}</p><p>{data.notes.gatewayCharges}</p></section></>}
  </main>;
}
