"use client";
import{createClient}from"@supabase/supabase-js";import Link from"next/link";import{useRouter}from"next/navigation";import{useCallback,useEffect,useMemo,useState}from"react";import styles from"./platform-fee-invoice-admin.module.css";
type Candidate={id:string;paymentId:string;businessSegment:string;platformCommissionAmount:string;cgstAmount:string;sgstAmount:string;igstAmount:string;currency:string;totalAmount:number;payment:{paymentNumber:string;booking:{bookingNumber:string;bookingStatus:string;trackingStatus:string}};vendor:{vendorCode:string;companyName:string}};
type Invoice={id:string;invoiceNumber:string|null;financialYear:string;status:string;businessSegment:string;bookingNumber:string;paymentNumber:string;quotationNumber:string;currency:string;taxableAmount:string;cgstAmount:string;sgstAmount:string;igstAmount:string;totalAmount:string;tcsAmount:string;vendorLegalName:string;snapshotChecksum:string;createdBy:string;issuedBy:string|null;createdAt:string;issuedAt:string|null};
const money=(value:number|string)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(Number(value));
export function PlatformFeeInvoiceAdmin({supabaseUrl,publishableKey}:{supabaseUrl:string;publishableKey:string}){const router=useRouter(),client=useMemo(()=>supabaseUrl&&publishableKey?createClient(supabaseUrl,publishableKey):null,[supabaseUrl,publishableKey]);const[status,setStatus]=useState(""),[candidates,setCandidates]=useState<Candidate[]>([]),[invoices,setInvoices]=useState<Invoice[]>([]),[currentUserId,setCurrentUserId]=useState(""),[supplierConfigured,setSupplierConfigured]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[success,setSuccess]=useState(false);
const session=useCallback(async()=>{if(!client)throw new Error("Office authentication is not configured.");const{data}=await client.auth.getSession();if(!data.session){router.replace("/admin/login?returnTo=/admin/tax-invoices");throw new Error("Office session expired.");}return data.session;},[client,router]);
const api=useCallback(async(path:string,init?:RequestInit)=>{const auth=await session(),response=await fetch(path,{...init,cache:"no-store",headers:{Authorization:`Bearer ${auth.access_token}`,...(init?.body?{"Content-Type":"application/json"}:{}),...init?.headers}}),payload=await response.json();if(!response.ok||!payload.success)throw new Error(payload?.error?.message||"Invoice operation failed.");return payload.data;},[session]);
const load=useCallback(async()=>{setBusy(true);try{const data=await api(`/api/admin/platform-fee-invoices${status?`?status=${status}`:""}`);setCandidates(data.candidates);setInvoices(data.invoices);setCurrentUserId(data.currentUserId);setSupplierConfigured(data.supplierConfigured);}catch(error){setSuccess(false);setMessage(error instanceof Error?error.message:"Unable to load invoices.");}finally{setBusy(false);}},[api,status]);useEffect(()=>{void load();},[load]);
async function act(path:string,body:unknown,text:string){setBusy(true);setMessage("");try{await api(path,{method:"POST",body:JSON.stringify(body)});setSuccess(true);setMessage(text);await load();}catch(error){setSuccess(false);setMessage(error instanceof Error?error.message:"Invoice operation failed.");}finally{setBusy(false);}}
async function download(invoice:Invoice,format:"pdf"|"csv"){setBusy(true);try{const auth=await session(),response=await fetch(`/api/admin/platform-fee-invoices/${invoice.id}/${format}`,{cache:"no-store",headers:{Authorization:`Bearer ${auth.access_token}`}});if(!response.ok){const payload=await response.json();throw new Error(payload?.error?.message||"Download failed.");}const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;if(format==="pdf"){link.target="_blank";link.rel="noopener noreferrer";}else link.download=`${invoice.invoiceNumber?.replaceAll("/","-")}.csv`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}catch(error){setSuccess(false);setMessage(error instanceof Error?error.message:"Download failed.");}finally{setBusy(false);}}
return <main className={styles.page}><header><div><p>FINANCE CONTROL</p><h1>Vendor commission tax invoices</h1><span>Issue immutable PDF and CSV records from approved commission snapshots.</span></div><div><Link href="/admin/finance">Finance overview</Link><button onClick={()=>void load()} disabled={busy}>Refresh</button></div></header>{message&&<p className={success?styles.success:styles.error}>{message}</p>}{!supplierConfigured&&<p className={styles.warning}>Configure EasyMovers legal name, registered address, GSTIN and commission SAC in Railway before creating invoice drafts.</p>}
<section className={styles.candidates}><div><h2>Ready to draft</h2><p>Only completed services with approved commission terms appear here.</p></div>{candidates.length?candidates.map(item=><article key={item.id}><div><strong>{item.vendor.companyName}</strong><span>{item.payment.booking.bookingNumber} · {item.businessSegment.replaceAll("_"," ")}</span></div><b>{money(item.totalAmount)}</b><button disabled={busy||!supplierConfigured} onClick={()=>void act("/api/admin/platform-fee-invoices",{commercialTermRequestId:item.id},"Invoice draft created for independent checker issuance.")}>Create draft</button></article>):<p>No completed commission approvals are awaiting invoice creation.</p>}</section>
<section className={styles.toolbar}><label>Invoice status<select value={status} onChange={event=>setStatus(event.target.value)}><option value="">All invoices</option><option value="DRAFT">Draft</option><option value="ISSUED">Issued</option><option value="CANCELLED">Cancelled</option></select></label><span>{invoices.length} invoice{invoices.length===1?"":"s"}</span></section><section className={styles.list}>{invoices.length?invoices.map(item=><article key={item.id}><div className={styles.title}><div><span>{item.status}</span><h2>{item.invoiceNumber||"Draft invoice"}</h2><p>{item.vendorLegalName} · {item.bookingNumber}</p></div><strong>{money(item.totalAmount)}</strong></div><dl><div><dt>Taxable commission</dt><dd>{money(item.taxableAmount)}</dd></div><div><dt>GST</dt><dd>{money(Number(item.cgstAmount)+Number(item.sgstAmount)+Number(item.igstAmount))}</dd></div><div><dt>TCS information</dt><dd>{money(item.tcsAmount)}</dd></div><div><dt>Segment</dt><dd>{item.businessSegment.replaceAll("_"," ")}</dd></div></dl><div className={styles.actions}>{item.status==="DRAFT"&&<><button disabled={busy||item.createdBy===currentUserId} onClick={()=>void act(`/api/admin/platform-fee-invoices/${item.id}/issue`,{},"Tax invoice issued and locked.")}>Issue invoice</button>{item.createdBy===currentUserId&&<small>Another billing-authorised user must issue this draft.</small>}</>}{item.status==="ISSUED"&&<><button onClick={()=>void download(item,"pdf")} disabled={busy}>Open PDF / print</button><button onClick={()=>void download(item,"csv")} disabled={busy}>Download CSV</button><small>Integrity: {item.snapshotChecksum.slice(0,12)}…</small></>}</div></article>):<p>No invoices match this status.</p>}</section></main>}
