"use client";

import { createClient } from "@supabase/supabase-js";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import styles from "./vendor-settlement-admin.module.css";

type Settlement = { id:string;vendorId:string;amount:string;currency:string;status:string;settlementReference:string|null;expectedAt:string|null;settledAt:string|null;failureReason:string|null;remarks:string|null;createdBy:string|null;reviewedBy:string|null;reviewedAt:string|null;reviewNote:string|null;createdAt:string;vendor:{vendorCode:string;companyName:string};payment:{paymentNumber:string;paidAmount:string;booking:{bookingNumber:string}} };
type Candidate = { id:string;paymentNumber:string;bookingNumber:string;vendorId:string;vendor:{vendorCode:string;companyName:string};currency:string;customerReceived:number;vendorNetPayable:number;available:number };
const currency = (amount:number|string, code="INR") => new Intl.NumberFormat("en-IN",{style:"currency",currency:code,maximumFractionDigits:2}).format(Number(amount));

export function VendorSettlementAdmin({supabaseUrl,publishableKey,initialStatus="PENDING"}:{supabaseUrl:string;publishableKey:string;initialStatus?:string}) {
  const router=useRouter();
  const client=useMemo(()=>supabaseUrl&&publishableKey?createClient(supabaseUrl,publishableKey):null,[supabaseUrl,publishableKey]);
  const [settlements,setSettlements]=useState<Settlement[]>([]); const [candidates,setCandidates]=useState<Candidate[]>([]); const [currentUserId,setCurrentUserId]=useState("");
  const [status,setStatus]=useState(initialStatus); const [selectedId,setSelectedId]=useState(""); const [candidateId,setCandidateId]=useState("");
  const [amount,setAmount]=useState(""); const [expectedAt,setExpectedAt]=useState(""); const [remarks,setRemarks]=useState(""); const [reviewNote,setReviewNote]=useState("");
  const [reference,setReference]=useState(""); const [failureReason,setFailureReason]=useState(""); const [message,setMessage]=useState(""); const [success,setSuccess]=useState(false); const [busy,setBusy]=useState(false);
  const request=useCallback(async(path:string,init?:RequestInit)=>{if(!client)throw new Error("Office authentication is not configured.");const {data}=await client.auth.getSession();if(!data.session){router.replace("/admin/login?returnTo=/admin/vendor-settlements");throw new Error("Office session expired.");}const response=await fetch(path,{...init,cache:"no-store",headers:{Authorization:`Bearer ${data.session.access_token}`,...(init?.body?{"Content-Type":"application/json"}:{}),...init?.headers}});const payload=await response.json();if(!response.ok||!payload.success)throw new Error(payload?.error?.message||"Settlement operation failed.");return payload.data;},[client,router]);
  const load=useCallback(async()=>{setBusy(true);setMessage("");try{const data=await request(`/api/admin/vendor-settlements?status=${status}`);setSettlements(data.settlements);setCandidates(data.candidates);setCurrentUserId(data.currentUserId);setSelectedId((id:string)=>data.settlements.some((item:Settlement)=>item.id===id)?id:data.settlements[0]?.id||"");}catch(error){setSuccess(false);setMessage(error instanceof Error?error.message:"Unable to load settlements.");}finally{setBusy(false);}},[request,status]);
  useEffect(()=>{void load();},[load]);
  const selected=settlements.find(item=>item.id===selectedId)||null; const candidate=candidates.find(item=>item.id===candidateId)||null; const ownRequest=selected?.createdBy===currentUserId;
  useEffect(()=>{if(candidate)setAmount(candidate.available.toFixed(2));},[candidate]);
  async function act(path:string,body:unknown,successMessage:string){setBusy(true);setMessage("");try{await request(path,{method:"POST",body:JSON.stringify(body)});setSuccess(true);setMessage(successMessage);setReviewNote("");setReference("");setFailureReason("");await load();}catch(error){setSuccess(false);setMessage(error instanceof Error?error.message:"Settlement operation failed.");}finally{setBusy(false);}}
  return <main className={styles.page}><header><div><p>FINANCE CONTROL</p><h1>Vendor settlements</h1><span>Separate customer collections from controlled vendor payouts.</span></div><div><Link href="/admin/commercial-terms">Commission readiness</Link><button onClick={()=>void load()} disabled={busy}>Refresh</button></div></header>
    {message&&<p className={success?styles.success:styles.error}>{message}</p>}
    <section className={styles.create}><div><h2>Create payout request</h2><p>Only customer-funded, commission-locked amounts are available.</p></div><label>Payable booking<select value={candidateId} onChange={event=>setCandidateId(event.target.value)}><option value="">Select vendor and booking</option>{candidates.map(item=><option key={item.id} value={item.id}>{item.vendor.companyName} · {item.bookingNumber} · {currency(item.available,item.currency)}</option>)}</select></label><label>Amount<input type="number" min="0.01" step="0.01" max={candidate?.available} value={amount} onChange={event=>setAmount(event.target.value)}/></label><label>Expected date<input type="date" value={expectedAt} onChange={event=>setExpectedAt(event.target.value)}/></label><label className={styles.wide}>Maker note<input value={remarks} maxLength={1000} onChange={event=>setRemarks(event.target.value)} placeholder="Purpose or payout cycle"/></label><button disabled={busy||!candidate||!amount} onClick={()=>candidate&&void act("/api/admin/vendor-settlements",{vendorId:candidate.vendorId,paymentId:candidate.id,amount,expectedAt:expectedAt||null,remarks},"Settlement request submitted for independent approval.")}>Submit for approval</button></section>
    <section className={styles.toolbar}><label>Status<select value={status} onChange={event=>setStatus(event.target.value)}><option value="PENDING">Awaiting checker</option><option value="PROCESSING">Approved / processing</option><option value="SETTLED">Settled</option><option value="FAILED">Failed</option><option value="REJECTED">Rejected</option><option value="ALL">All</option></select></label><span>{settlements.length} record{settlements.length===1?"":"s"}</span></section>
    <div className={styles.workspace}><section className={styles.list}>{settlements.length?settlements.map(item=><button key={item.id} className={item.id===selectedId?styles.selected:""} onClick={()=>{setSelectedId(item.id);setMessage("");}}><span><strong>{item.vendor.companyName}</strong><em>{item.status}</em></span><b>{currency(item.amount,item.currency)}</b><small>{item.payment.booking.bookingNumber} · {item.payment.paymentNumber}</small></button>):<p>No settlements in this queue.</p>}</section>
      <section className={styles.detail}>{!selected?<p>Select a settlement to review.</p>:<><div className={styles.title}><div><span>{selected.vendor.vendorCode}</span><h2>{selected.vendor.companyName}</h2><p>{selected.payment.booking.bookingNumber} · {selected.payment.paymentNumber}</p></div><strong>{currency(selected.amount,selected.currency)}</strong></div><dl><div><dt>Status</dt><dd>{selected.status}</dd></div><div><dt>Customer received</dt><dd>{currency(selected.payment.paidAmount,selected.currency)}</dd></div><div><dt>Requested</dt><dd>{new Date(selected.createdAt).toLocaleString("en-IN")}</dd></div>{selected.settlementReference&&<div><dt>Bank reference</dt><dd>{selected.settlementReference}</dd></div>}</dl>{selected.remarks&&<p className={styles.note}><b>Maker note:</b> {selected.remarks}</p>}
        {selected.status==="PENDING"&&<div className={styles.action}><h3>Independent checker decision</h3>{ownRequest&&<p className={styles.warning}>You created this request. Another authorised checker must review it.</p>}<textarea value={reviewNote} onChange={event=>setReviewNote(event.target.value)} placeholder="Reason required for rejection"/><div><button disabled={busy||ownRequest} onClick={()=>void act(`/api/admin/vendor-settlements/${selected.id}/review`,{decision:"APPROVED",reviewNote},"Settlement approved for payment processing.")}>Approve</button><button className={styles.danger} disabled={busy||ownRequest||!reviewNote.trim()} onClick={()=>void act(`/api/admin/vendor-settlements/${selected.id}/review`,{decision:"REJECTED",reviewNote},"Settlement request rejected.")}>Reject</button></div></div>}
        {selected.status==="PROCESSING"&&<div className={styles.action}><h3>Record payout result</h3><input value={reference} onChange={event=>setReference(event.target.value)} placeholder="Bank / gateway reference"/><input value={failureReason} onChange={event=>setFailureReason(event.target.value)} placeholder="Failure reason (required if failed)"/><div><button disabled={busy||!reference.trim()} onClick={()=>void act(`/api/admin/vendor-settlements/${selected.id}/complete`,{outcome:"SETTLED",settlementReference:reference},"Vendor payout marked settled.")}>Mark settled</button><button className={styles.danger} disabled={busy||!failureReason.trim()} onClick={()=>void act(`/api/admin/vendor-settlements/${selected.id}/complete`,{outcome:"FAILED",failureReason},"Vendor payout marked failed. Create a new request to retry.")}>Mark failed</button></div></div>}
        {selected.reviewNote&&<p className={styles.note}><b>Checker note:</b> {selected.reviewNote}</p>}{selected.failureReason&&<p className={styles.warning}><b>Failure:</b> {selected.failureReason}</p>}</>}</section></div>
  </main>;
}
