"use client";

import { createClient } from "@supabase/supabase-js";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import styles from "./vendor-operations-admin.module.css";

type VendorSummary = { id: string; vendorCode: string; companyName: string; ownerName: string; city: string | null; state: string | null; status: string; _count: { serviceAreas: number; vehicles: number; documents: number; assignedBookings: number } };
type LocationOption = { id: string; code: string; city: string; state: string; status: string };
type AreaDraft = { scope: "WITHIN_CITY" | "WITHIN_STATE" | "PAN_INDIA"; locationId: string; pins: string };
type Detail = { vendor: VendorSummary & { ownerMobile: string; ownerEmail: string | null; businessType: string; pincode: string | null; serviceAreas: Array<{ id: string; scope: AreaDraft["scope"]; originCity: string | null; originState: string | null; serviceablePostalCodes: string[]; active: boolean }>; serviceOfferings: Array<{ id: string; serviceType: string; title: string; active: boolean }>; vehicles: Array<{ id: string; registrationNumber: string; vehicleType: string; status: string; isActive: boolean }>; documents: Array<{ id: string; documentType: string; verificationStatus: string; isMandatory: boolean; isActive: boolean }>; bankAccounts: Array<{ id: string; bankName: string; verified: boolean; isPrimary: boolean }>; _count: { assignedBookings: number; quotations: number; payments: number } }; locationOptions: LocationOption[]; readiness: { activeServiceAreas: number; activeServiceOfferings: number; activeVehicles: number; verifiedMandatoryDocuments: number; mandatoryDocuments: number; verifiedBankAccounts: number; blockers: Array<{ code: string; message: string }>; operationallyReady: boolean }; capabilities: { canManage: boolean; canActivate: boolean } };
const label = (value: string) => value.replaceAll("_", " ").toLowerCase().replace(/^./, c => c.toUpperCase());
const serviceTypes = ["HOUSEHOLD_RELOCATION", "OFFICE_RELOCATION", "CORPORATE_RELOCATION", "VEHICLE_TRANSPORT", "COMMERCIAL_GOODS", "WAREHOUSING", "PACKING_ONLY", "LOADING_UNLOADING", "INSTALLATION_UNINSTALLATION"];

export function VendorOperationsAdmin({ supabaseUrl, publishableKey }: { supabaseUrl: string; publishableKey: string }) {
  const router = useRouter();
  const client = useMemo(() => supabaseUrl && publishableKey ? createClient(supabaseUrl, publishableKey) : null, [supabaseUrl, publishableKey]);
  const [vendors, setVendors] = useState<VendorSummary[]>([]); const [selected, setSelected] = useState<Detail | null>(null);
  const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [search, setSearch] = useState("");
  const [areas, setAreas] = useState<AreaDraft[]>([]); const [offerings, setOfferings] = useState<string[]>([]);
  const request = useCallback(async (path: string, init?: RequestInit) => {
    if (!client) throw new Error("Office authentication is not configured.");
    const { data } = await client.auth.getSession();
    if (!data.session) { router.replace("/admin/login?returnTo=/admin/vendors"); throw new Error("Office session expired."); }
    const response = await fetch(path, { ...init, cache: "no-store", headers: { Authorization: `Bearer ${data.session.access_token}`, ...(init?.body ? { "Content-Type": "application/json" } : {}), ...init?.headers } });
    const payload = await response.json(); if (!response.ok || !payload.success) throw new Error(payload?.error?.message || "Vendor operation failed.");
    return payload.data;
  }, [client, router]);
  const load = useCallback(async () => { setLoading(true); setMessage(""); try { const query = new URLSearchParams({ page: "1", pageSize: "100" }); if (search.trim()) query.set("search", search.trim()); const data = await request(`/api/admin/vendors?${query}`); setVendors(data.vendors); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load vendors."); } finally { setLoading(false); } }, [request, search]);
  const open = useCallback(async (id: string) => { setLoading(true); setMessage(""); try { const detail: Detail = await request(`/api/admin/vendors/${encodeURIComponent(id)}`); setSelected(detail); setOfferings(detail.vendor.serviceOfferings.filter(item => item.active).map(item => item.serviceType)); setAreas(detail.vendor.serviceAreas.filter(item => item.active).map(area => ({ scope: area.scope, locationId: detail.locationOptions.find(location => area.scope === "WITHIN_CITY" ? location.city.toLowerCase() === area.originCity?.toLowerCase() && location.state.toLowerCase() === area.originState?.toLowerCase() : location.state.toLowerCase() === area.originState?.toLowerCase())?.id || "", pins: area.serviceablePostalCodes.join(", ") }))); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load vendor readiness."); } finally { setLoading(false); } }, [request]);
  useEffect(() => { void load(); }, [load]);
  function updateArea(index: number, patch: Partial<AreaDraft>) { setAreas(current => current.map((area, position) => position === index ? { ...area, ...patch } : area)); }
  async function saveConfiguration(event: FormEvent) { event.preventDefault(); if (!selected || loading) return; setLoading(true); setMessage(""); try { await request(`/api/admin/vendors/${selected.vendor.id}/configuration`, { method: "PUT", body: JSON.stringify({ areas: areas.map(area => ({ scope: area.scope, locationId: area.scope === "PAN_INDIA" ? undefined : area.locationId, serviceablePostalCodes: area.pins.split(/[\s,]+/).filter(Boolean) })), serviceTypes: offerings }) }); await open(selected.vendor.id); await load(); setMessage("Vendor service configuration saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save vendor configuration."); setLoading(false); } }
  const editable = selected?.capabilities.canManage && selected.vendor.status !== "ACTIVE";
  return <main className={styles.page}>
    <header className={styles.heading}><div><p>PARTNER OPERATIONS</p><h1>Vendor readiness</h1><span>Verify operational capacity before activating a moving partner.</span></div><button onClick={() => void load()}>Refresh</button></header>
    <form className={styles.search} onSubmit={event => { event.preventDefault(); void load(); }}><input value={search} maxLength={100} onChange={event => setSearch(event.target.value)} placeholder="Search vendor, code, owner or city…"/><button>Search</button></form>
    {message && <p className={styles.error}>{message}</p>}
    <div className={styles.workspace}><section className={styles.list}><strong>{vendors.length} vendors</strong>{vendors.map(vendor => <button key={vendor.id} className={selected?.vendor.id === vendor.id ? styles.selected : ""} onClick={() => void open(vendor.id)}><span><b>{vendor.companyName}</b><em className={styles[vendor.status]}>{label(vendor.status)}</em></span><small>{vendor.vendorCode} · {vendor.city || "City pending"}</small><small>{vendor._count.serviceAreas} areas · {vendor._count.vehicles} vehicles · {vendor._count.documents} documents</small></button>)}</section>
      <section className={styles.detail}>{!selected ? <div className={styles.empty}>{loading ? "Loading vendors…" : "Select a vendor to review operational readiness."}</div> : <>
        <div className={styles.title}><div><em className={selected.readiness.operationallyReady ? styles.ready : styles.pending}>{selected.readiness.operationallyReady ? "Operationally ready" : "Setup incomplete"}</em><h2>{selected.vendor.companyName}</h2><p>{selected.vendor.vendorCode} · {selected.vendor.ownerName}</p></div></div>
        <div className={styles.cards}><article><span>Service areas</span><strong>{selected.readiness.activeServiceAreas}</strong></article><article><span>Service offerings</span><strong>{selected.readiness.activeServiceOfferings}</strong></article><article><span>Active vehicles</span><strong>{selected.readiness.activeVehicles}</strong></article><article><span>Verified documents</span><strong>{selected.readiness.verifiedMandatoryDocuments}/{selected.readiness.mandatoryDocuments}</strong></article><article><span>Verified banks</span><strong>{selected.readiness.verifiedBankAccounts}</strong></article></div>
        {selected.readiness.blockers.length > 0 && <div className={styles.blockers}><strong>Activation blockers</strong>{selected.readiness.blockers.map(blocker => <span key={blocker.code}>{blocker.message}</span>)}</div>}
        {editable && <form className={styles.configuration} onSubmit={saveConfiguration}><div className={styles.configTitle}><div><h3>Service configuration</h3><span>Only registered EasyMovers service locations can be assigned.</span></div><button type="button" onClick={() => setAreas(current => [...current, { scope: "WITHIN_CITY", locationId: selected.locationOptions[0]?.id || "", pins: "" }])}>Add area</button></div>
          <div className={styles.areaRows}>{areas.length ? areas.map((area, index) => <div className={styles.areaRow} key={`${index}-${area.scope}-${area.locationId}`}><select aria-label={`Area ${index + 1} scope`} value={area.scope} onChange={event => updateArea(index, { scope: event.target.value as AreaDraft["scope"], locationId: event.target.value === "PAN_INDIA" ? "" : area.locationId })}><option value="WITHIN_CITY">Within city</option><option value="WITHIN_STATE">Within state</option><option value="PAN_INDIA">Pan India</option></select>{area.scope !== "PAN_INDIA" && <select aria-label={`Area ${index + 1} location`} required value={area.locationId} onChange={event => updateArea(index, { locationId: event.target.value })}><option value="">Select registered location</option>{selected.locationOptions.filter((location, position, options) => area.scope !== "WITHIN_STATE" || options.findIndex(candidate => candidate.state === location.state) === position).map(location => <option key={location.id} value={location.id}>{area.scope === "WITHIN_STATE" ? location.state : `${location.city}, ${location.state}`}</option>)}</select>}<input aria-label={`Area ${index + 1} PIN codes`} disabled={area.scope === "PAN_INDIA"} placeholder="Optional PIN codes" value={area.pins} onChange={event => updateArea(index, { pins: event.target.value.replace(/[^0-9,\s]/g, "") })}/><button type="button" className={styles.remove} onClick={() => setAreas(current => current.filter((_, position) => position !== index))}>Remove</button></div>) : <p>No service areas selected.</p>}</div>
          <fieldset><legend>Service offerings</legend><div className={styles.offeringGrid}>{serviceTypes.map(serviceType => <label key={serviceType}><input type="checkbox" checked={offerings.includes(serviceType)} onChange={event => setOfferings(current => event.target.checked ? [...current, serviceType] : current.filter(item => item !== serviceType))}/><span>{label(serviceType)}</span></label>)}</div></fieldset><button className={styles.save} disabled={loading}>{loading ? "Saving…" : "Save service configuration"}</button>
        </form>}
        {selected.vendor.status === "ACTIVE" && selected.capabilities.canManage && <p className={styles.next}>Suspend this active vendor before changing service areas or offerings.</p>}
        <section className={styles.matrix}><h3>Current service areas</h3>{selected.vendor.serviceAreas.length ? selected.vendor.serviceAreas.map(area => <p key={area.id}><b>{label(area.scope)}</b> — {area.originCity || area.originState || "Pan India"} <em>{area.active ? "Active" : "Inactive"}</em></p>) : <p>No service areas configured.</p>}<h3>Current service offerings</h3>{selected.vendor.serviceOfferings.length ? selected.vendor.serviceOfferings.map(offering => <p key={offering.id}><b>{label(offering.serviceType)}</b> <em>{offering.active ? "Active" : "Inactive"}</em></p>) : <p>No service offerings configured.</p>}</section>
      </>}</section>
    </div>
  </main>;
}
