import {NextResponse} from "next/server";
import {randomUUID} from "node:crypto";
import {createClient} from "@supabase/supabase-js";
import {prisma} from "@/lib/prisma";
import {checkOrigin,readDraftSession} from "@/lib/enquiry-session";
export const runtime="nodejs";
function reply(body:object,status=200){return NextResponse.json(body,{status,headers:{"Cache-Control":"no-store"}})}
async function storage(){const url=process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL;const key=process.env.SUPABASE_SERVICE_ROLE_KEY;const bucket=process.env.INVENTORY_PHOTO_BUCKET;if(!url||!key||!bucket)throw Error("CONFIG");const client=createClient(url,key,{auth:{persistSession:false}});const {data,error}=await client.storage.getBucket(bucket);if(error||!data||data.public)throw Error("CONFIG");return client.storage.from(bucket)}
export async function GET(req:Request){try{const reference=new URL(req.url).searchParams.get("reference")||"";const session=readDraftSession(req,reference);if(!session)return reply({success:false,message:"Verify your mobile to continue."},401);const inventory=await prisma.inventory.findFirst({where:{referenceId:reference,leadId:session.id},select:{callbackRequested:true,callbackSlot:true,photos:{select:{id:true,imageUrl:true}}}});if(!inventory)return reply({success:false},404);const photos=await Promise.all(inventory.photos.map(async photo=>{try{const {data}=await (await storage()).createSignedUrl(photo.imageUrl,300);return {id:photo.id,url:data?.signedUrl}}catch{return {id:photo.id}}}));return reply({success:true,callbackSlot:inventory.callbackSlot,photos})}catch{return reply({success:false,message:"Unable to load assistance details."},503)}}
export async function POST(req:Request){let objectKey="";let bucket:Awaited<ReturnType<typeof storage>>|undefined;try{
 try{checkOrigin(req)}catch{return reply({success:false,message:"Invalid request origin."},403)}
 const isPhoto=req.headers.get("content-type")?.includes("multipart/form-data");
 const length=Number(req.headers.get("content-length")||0);if(length>9*1024*1024)return reply({success:false,message:"Maximum photo size is 8 MB."},413);
 const reader=req.body?.getReader();if(!reader)return reply({success:false},400);const chunks:Uint8Array[]=[];let size=0;while(true){const part=await reader.read();if(part.done)break;size+=part.value.length;if(size>(isPhoto?9*1024*1024:2000)){await reader.cancel();return reply({success:false,message:"Request too large."},413)}chunks.push(part.value)}const bytesBody=Buffer.concat(chunks);const raw=isPhoto?await new Response(bytesBody,{headers:{"Content-Type":req.headers.get("content-type")||""}}).formData():JSON.parse(bytesBody.toString("utf8"));const get=(key:string)=>raw instanceof FormData?raw.get(key):raw[key];
 const reference=String(get("reference")||"");const session=readDraftSession(req,reference);if(!session)return reply({success:false,message:"Verify your mobile to continue."},401);
 const version=String(get("version")||"");if(!Number.isFinite(Date.parse(version)))return reply({success:false,message:"Reopen the draft before continuing."},400);
 const inventory=await prisma.inventory.findFirst({where:{referenceId:reference,leadId:session.id,status:"DRAFT"},select:{id:true,_count:{select:{photos:true}}}});if(!inventory)return reply({success:false,message:"This draft is unavailable or already submitted."},409);
 let slot:string|undefined;
 if(isPhoto){const file=get("file");if(!(file instanceof File)||file.size>8*1024*1024||file.size<12)return reply({success:false,message:"Choose a JPEG, PNG or WebP photo under 8 MB."},400);if(inventory._count.photos>=10)return reply({success:false,message:"You can upload up to 10 photos."},400);const bytes=Buffer.from(await file.arrayBuffer());const type=bytes[0]===255&&bytes[1]===216&&bytes[2]===255?"image/jpeg":bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))?"image/png":bytes.toString("ascii",0,4)==="RIFF"&&bytes.toString("ascii",8,12)==="WEBP"?"image/webp":"";if(!type||file.type!==type)return reply({success:false,message:"The file must be a valid JPEG, PNG or WebP photo."},400);bucket=await storage();objectKey=`${session.id}/${inventory.id}/${randomUUID()}`;const {error}=await bucket.upload(objectKey,bytes,{contentType:type,upsert:false});if(error)throw Error("UPLOAD");}
 else{slot=String(get("slot")||"");if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}\+05:30$/.test(slot)||!Number.isFinite(Date.parse(slot))||new Date(Date.parse(slot)+330*60000).toISOString().slice(0,16)!==slot.slice(0,16)||Date.parse(slot)<=Date.now()||Date.parse(slot)>Date.now()+30*86400000)return reply({success:false,message:"Choose a callback time within the next 30 days (India time)."},400)}
 const result=await prisma.$transaction(async tx=>{const updated=await tx.inventory.updateMany({where:{id:inventory.id,leadId:session.id,status:"DRAFT",updatedAt:new Date(version)},data:isPhoto?{photoInventoryRequested:true}:{callbackRequested:true,callbackSlot:slot}});if(updated.count!==1)throw Error("CONFLICT");if(isPhoto){const count=await tx.inventoryPhoto.count({where:{inventoryId:inventory.id}});if(count>=10)throw Error("CONFLICT");await tx.inventoryPhoto.create({data:{inventoryId:inventory.id,imageUrl:objectKey}})}else{await tx.lead.update({where:{id:session.id},data:{status:"INVENTORY_PENDING"}})}return tx.inventory.findUniqueOrThrow({where:{id:inventory.id},select:{updatedAt:true}})});
 return reply({success:true,version:result.updatedAt.toISOString(),message:isPhoto?"Photo saved for inventory review.":"Callback requested. Your inventory remains a draft; an executive will confirm the slot."});
 }catch(error){if(objectKey&&bucket)await bucket.remove([objectKey]).catch(()=>{});const code=error instanceof Error?error.message:"";return reply({success:false,message:code==="CONFLICT"?"Draft changed. Reopen it before trying again.":code==="CONFIG"?"Photo uploads are not configured yet. You can request a callback instead.":"Unable to save this request. Please retry."},code==="CONFLICT"?409:503)}}
