import { randomUUID } from "node:crypto";
import { MoveSurveyStatus } from "@prisma/client";
import { createClient } from "@supabase/supabase-js";
import { NextResponse } from "next/server";
import { checkOrigin, readDraftSession } from "@/lib/enquiry-session";
import { prisma } from "@/lib/prisma";
export const runtime="nodejs";export const dynamic="force-dynamic";
const reply=(body:object,status=200)=>NextResponse.json(body,{status,headers:{"Cache-Control":"no-store"}});
async function bucket(){const url=process.env.SUPABASE_URL||process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY,name=process.env.SURVEY_MEDIA_BUCKET||process.env.INVENTORY_PHOTO_BUCKET;if(!url||!key||!name)throw Error("CONFIG");const storage=createClient(url,key,{auth:{persistSession:false}}).storage;const {data,error}=await storage.getBucket(name);if(error||!data||data.public)throw Error("CONFIG");return storage.from(name)}
export async function POST(request:Request,context:{params:Promise<{surveyId:string}>}){let objectKey="",storage:Awaited<ReturnType<typeof bucket>>|undefined;try{checkOrigin(request);const length=Number(request.headers.get("content-length")||0);if(length>3*1024*1024)return reply({success:false,message:"Maximum survey photo size is 2 MB."},413);const form=await request.formData();const reference=String(form.get("reference")||""),session=readDraftSession(request,reference);if(!session)return reply({success:false,message:"Verify the registered mobile number to continue."},401);const {surveyId}=await context.params;const roomId=String(form.get("roomId")||""),caption=String(form.get("caption")||"").trim().slice(0,300),file=form.get("file");if(!(file instanceof File)||file.size<12||file.size>2*1024*1024)return reply({success:false,message:"Choose a JPEG, PNG or WebP photo under 2 MB."},400);const survey=await prisma.moveSurvey.findFirst({where:{id:surveyId,leadId:session.id,status:{in:[MoveSurveyStatus.REQUESTED,MoveSurveyStatus.IN_PROGRESS,MoveSurveyStatus.RETURNED_FOR_CORRECTION]},rooms:{some:{id:roomId}}},select:{id:true,_count:{select:{media:true}}}});if(!survey)return reply({success:false,message:"This survey room is unavailable or locked."},409);if(survey._count.media>=60)return reply({success:false,message:"A survey may contain up to 60 photographs."},409);const bytes=Buffer.from(await file.arrayBuffer());const mime=bytes[0]===255&&bytes[1]===216&&bytes[2]===255?"image/jpeg":bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))?"image/png":bytes.toString("ascii",0,4)==="RIFF"&&bytes.toString("ascii",8,12)==="WEBP"?"image/webp":"";if(!mime||file.type!==mime)return reply({success:false,message:"The file must be a valid JPEG, PNG or WebP photo."},400);storage=await bucket();objectKey=`surveys/${session.id}/${survey.id}/${roomId}/${randomUUID()}`;const {error}=await storage.upload(objectKey,bytes,{contentType:mime,upsert:false});if(error)throw Error("UPLOAD");const media=await prisma.$transaction(async tx=>{const count=await tx.moveSurveyMedia.count({where:{surveyId}});if(count>=60)throw Error("LIMIT");const record=await tx.moveSurveyMedia.create({data:{surveyId,roomId,objectKey,mimeType:mime,fileSize:file.size,caption:caption||null,uploadedByType:"CUSTOMER",uploadedById:session.id}});await tx.moveSurvey.update({where:{id:surveyId},data:{status:MoveSurveyStatus.IN_PROGRESS,startedAt:new Date()}});return record});return reply({success:true,data:media,message:"Survey photo added to the selected room."},201)}catch(error){if(objectKey&&storage)await storage.remove([objectKey]).catch(()=>undefined);console.error("[SURVEY_MEDIA_UPLOAD_FAILED]",error);return reply({success:false,message:error instanceof Error&&error.message==="CONFIG"?"Survey photo storage is not configured.":"Unable to upload the survey photo."},503)}}
